# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_token_system.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15pb_token_system.proto\x12\x13token_system.api.v1\"G\n\x0e\x43reateTokenReq\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x02 \x01(\r\x12\x16\n\x0etokenPerSecond\x18\x03 \x01(\r\":\n\x0f\x43reateTokenResp\x12\'\n\x03\x65rr\x18\x01 \x01(\x0e\x32\x1a.token_system.api.v1.Error\"\x1e\n\rStartTokenReq\x12\r\n\x05topic\x18\x01 \x01(\t\"9\n\x0eStartTokenResp\x12\'\n\x03\x65rr\x18\x01 \x01(\x0e\x32\x1a.token_system.api.v1.Error\"+\n\x0bGetTokenReq\x12\r\n\x05topic\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\r\"7\n\x0cGetTokenResp\x12\'\n\x03\x65rr\x18\x01 \x01(\x0e\x32\x1a.token_system.api.v1.Error\"\x1f\n\x0e\x44\x65leteTokenReq\x12\r\n\x05topic\x18\x01 \x01(\t\":\n\x0f\x44\x65leteTokenResp\x12\'\n\x03\x65rr\x18\x01 \x01(\x0e\x32\x1a.token_system.api.v1.Error*\xc4\x02\n\x05\x45rror\x12\x06\n\x02OK\x10\x00\x12\x13\n\x0fTOPIC_NOT_EXIST\x10\x01\x12\x11\n\rTOPIC_IS_NULL\x10\x02\x12\x17\n\x13TOPIC_ALREADY_EXIST\x10\x03\x12\x17\n\x13TOPIC_INCORRECTNESS\x10\x04\x12\x13\n\x0fTOKEN_NOT_EXIST\x10\x05\x12\x17\n\x13TOKEN_ALREADY_START\x10\x06\x12\x13\n\x0fTOKEN_NOT_START\x10\x07\x12\x17\n\x13OUT_OF_RANGE_BUCKET\x10\x08\x12\x14\n\x10NOT_ENOUGH_TOKEN\x10\t\x12\x18\n\x14\x42UCKET_INCORRECTNESS\x10\x11\x12\"\n\x1eTOKEN_PER_SECOND_INCORRECTNESS\x10\x12\x12\x17\n\x13\x43REATE_TOKEN_FAILED\x10\x13\x12\x10\n\x0cSERVER_FAULT\x10\x14\x32\xe9\x02\n\x03\x41PI\x12Z\n\x0b\x43reateToken\x12#.token_system.api.v1.CreateTokenReq\x1a$.token_system.api.v1.CreateTokenResp\"\x00\x12W\n\nStartToken\x12\".token_system.api.v1.StartTokenReq\x1a#.token_system.api.v1.StartTokenResp\"\x00\x12Q\n\x08GetToken\x12 .token_system.api.v1.GetTokenReq\x1a!.token_system.api.v1.GetTokenResp\"\x00\x12Z\n\x0b\x44\x65leteToken\x12#.token_system.api.v1.DeleteTokenReq\x1a$.token_system.api.v1.DeleteTokenResp\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb_token_system_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ERROR._serialized_start=466
  _ERROR._serialized_end=790
  _CREATETOKENREQ._serialized_start=46
  _CREATETOKENREQ._serialized_end=117
  _CREATETOKENRESP._serialized_start=119
  _CREATETOKENRESP._serialized_end=177
  _STARTTOKENREQ._serialized_start=179
  _STARTTOKENREQ._serialized_end=209
  _STARTTOKENRESP._serialized_start=211
  _STARTTOKENRESP._serialized_end=268
  _GETTOKENREQ._serialized_start=270
  _GETTOKENREQ._serialized_end=313
  _GETTOKENRESP._serialized_start=315
  _GETTOKENRESP._serialized_end=370
  _DELETETOKENREQ._serialized_start=372
  _DELETETOKENREQ._serialized_end=403
  _DELETETOKENRESP._serialized_start=405
  _DELETETOKENRESP._serialized_end=463
  _API._serialized_start=793
  _API._serialized_end=1154
# @@protoc_insertion_point(module_scope)
